/* 
 * --------------------ECOBIKE RENTAL 1.0.1--------------------
 *
 * Design and Software Construction 20201
 *
 * Copyright (C) 2020 by Group 11
 *
 * Nguyen Thanh Long
 * Nguyen Hai Long
 * Nguyen Cong Luat
 * UN LyAn
 *
 * This software is created for academic purposes only. Not for
 * commercial purposes. We do not guarantee maintenance issues.
 *
 * ------------------------------------------------------------
 */
package com.hust.group11.ecobikerentalgroup11.boundary;

import com.hust.group11.ecobikerentalgroup11.MainEntry;
import com.hust.group11.ecobikerentalgroup11.controller.PaymentController;
import java.io.IOException;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Nguyen Thanh Long
 */
public class AddPayentMethodScreen extends javax.swing.JFrame {

    /**
     * Creates new form AddPayentMethodScreen
     */
    JFrame backScreen;
    private final PaymentController paymentController;

    public AddPayentMethodScreen(JFrame backScreen) throws SQLException, IOException {
        initComponents();
        this.setIconImage(ImageIO.read(getClass().getClassLoader().getResourceAsStream("img/icon_app.png")));
        this.backScreen = backScreen;
        this.paymentController = new PaymentController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namePaymentMethodFiled = new javax.swing.JTextField();
        namePaymentMethodLabel = new javax.swing.JLabel();
        cardCodeLabel = new javax.swing.JLabel();
        cardCodeField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameOwnerLabel = new javax.swing.JLabel();
        nameOwnerField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cvvCodeLabel = new javax.swing.JLabel();
        cvvCodeField = new javax.swing.JTextField();
        dateExpiredLabel = new javax.swing.JLabel();
        dateExpiredField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Payment Method");
        setResizable(false);

        namePaymentMethodLabel.setText("Name Payment Method");

        cardCodeLabel.setText("Card Code");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Payment Method Information");

        nameOwnerLabel.setText("Name Owner");

        jButton1.setText("Add Method");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMethodActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        cvvCodeLabel.setText("Cvv Code");

        dateExpiredLabel.setText("Date Expired");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namePaymentMethodLabel)
                            .addComponent(nameOwnerLabel)
                            .addComponent(cardCodeLabel)
                            .addComponent(cvvCodeLabel)
                            .addComponent(dateExpiredLabel))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(cardCodeField)
                            .addComponent(nameOwnerField)
                            .addComponent(namePaymentMethodFiled)
                            .addComponent(cvvCodeField)
                            .addComponent(dateExpiredField, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namePaymentMethodFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namePaymentMethodLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardCodeLabel)
                    .addComponent(cardCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameOwnerLabel)
                    .addComponent(nameOwnerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cvvCodeLabel)
                    .addComponent(cvvCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateExpiredLabel)
                    .addComponent(dateExpiredField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Handle event user click button add method. it will insert information
     * payment method of user
     *
     * @param evt
     */
    private void addMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMethodActionPerformed
        // System.out.println("add method here");
        String nameMethod = namePaymentMethodFiled.getText();
        String cardCode = cardCodeField.getText();
        String nameOwner = nameOwnerField.getText();
        String cvvCode = cvvCodeField.getText();
        String dateExpired = dateExpiredField.getText();
        int result = paymentController.createNewPaymentMethod(nameMethod, cardCode, nameOwner, cvvCode, dateExpired);
        if (result > 0) {
            MainEntry.move(this, backScreen);
            JOptionPane.showMessageDialog(backScreen, "Create success");
        } else {
            JOptionPane.showMessageDialog(this, "Create fail");
        }
    }//GEN-LAST:event_addMethodActionPerformed
    /**
     * Handle event user click button go back
     *
     * @param evt
     */
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        MainEntry.move(this, backScreen);
    }//GEN-LAST:event_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cardCodeField;
    private javax.swing.JLabel cardCodeLabel;
    private javax.swing.JTextField cvvCodeField;
    private javax.swing.JLabel cvvCodeLabel;
    private javax.swing.JTextField dateExpiredField;
    private javax.swing.JLabel dateExpiredLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nameOwnerField;
    private javax.swing.JLabel nameOwnerLabel;
    private javax.swing.JTextField namePaymentMethodFiled;
    private javax.swing.JLabel namePaymentMethodLabel;
    // End of variables declaration//GEN-END:variables
}
